### ISSUE TITLE
SonarQube version 9.6 breaks

### ISSUE THREAD

**Issue by Conzar** [markt-de/puppet-sonarqube#24]
SonarQube version 9.4 and 9.5 work without any issues.  Upgrading to 9.6.1.59531 causes the following error:

```sonar.service: Can't open PID file /opt/sonar/data/SonarQube.pid (yet?) after start: Operation not permitted```

If I manually change the permissions of the file system, I get the following error in the logs

```The database must be manually upgraded. Please backup the database and browse /setup```

But the web server never loads and /setup cannot be run.

Any ideas what the cause might be?  Something different in 9.6?

**Comment by IFV-oscar-vlugt** [comment]
Same issue here on CentOS 7 with Puppet6. Removing the PID line in /etc/systemd/system/sonar.service and disabling puppet solves it for now to get SonarQube running, however we need to do this manually after a Puppet Run to ensure it is running. Any solution yet?

**Comment by IFV-oscar-vlugt** [comment]
Setting pidfile => "../sonar-install/sonarqube-${version}/bin/linux-x86-64/SonarQube.pid" fixes it for us with 5.0.0 due to $sonar_home being /opt/sonar/data and the only .pid I could trace is on the location /opt/sonar-install/sonarqube-${version}/bin/linux-x86-64/SonarQube.pid .

**Comment by nambrosch** [comment]
Hi @fraenki I was wondering how this release is going - I'd like to use your module to install 9.7.  Thank you!

**Comment by fraenki** [comment]
I'm currently pretty busy. Could you try the latest commit from the master branch? AFAICT it should work. The next major release should be out in december.

**Comment by nambrosch** [comment]
Thanks for all of your work, I've been sticking with 9.5.0.56709 until your new version is ready.

**Comment by fraenki** [comment]
> SonarQube version 9.4 and 9.5 work without any issues. Upgrading to 9.6.1.59531 causes the following error:
> sonar.service: Can't open PID file /opt/sonar/data/SonarQube.pid (yet?) after start: Operation not permitted

I found out what is causing this issue. The startup script `sonar.sh` got a major overhaul in SonarQube 9.6:
https://github.com/SonarSource/sonarqube/commit/2f1b46f6363e67304acd90e75622e9d42e9a4fa9

As a result, the PID file setting was no longer working. This is finally fixed in version 5.1 of this module. SonarQube 9.8 successfully passed the acceptance tests.
