### ISSUE TITLE
Add support for puppetlabs/java 11

### ISSUE THREAD

**Issue by mj** [markt-de/puppet-sonarqube#34]
`puppetlabs/java` 11.0.0 has been [released in April](https://forge.puppet.com/modules/puppetlabs/java/changelog) with support for Debian 12. The `sonarqube` module should support this release.

**Comment by Lightning-** [comment]
fixed with 0bb6ad9

**Comment by mj** [comment]
@fraenki, @Lightning- , do you an ETA for a new release of `puppet-sonarqube` that contains the fix for this issue? Is there anything I can do to help?

**Comment by Lightning-** [comment]
@mj i'm so sorry, somehow this rotated out of my mind ... :pensive:  
i'll schedule a minor release for next week tuesday, stay tuned :)

**Comment by Lightning-** [comment]
decided to release a new major as the various changes in sonarqube (jdk17, runner→scanner) and our rework felt too heavy for just a minor one.

v6.0.0 is out and includes this fix too; thx 4 contributing :smiley:
